### ISSUE TITLE
点击左侧栏短消息时程序闪退

### ISSUE THREAD

**Issue by 4piu** [RanKKI/PSNine#1]
```
--------- beginning of crash
07-10 12:10:42.408 31295 31295 E AndroidRuntime: FATAL EXCEPTION: main
07-10 12:10:42.408 31295 31295 E AndroidRuntime: Process: club.ranleng.psnine, PID: 31295
07-10 12:10:42.408 31295 31295 E AndroidRuntime: java.lang.IllegalStateException: View 'adapter_list_root' with ID 2131755198 for field 'root' was of the wrong type. See cause for more info.
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at butterknife.internal.Utils.castView(Utils.java:113)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:105)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at club.ranleng.psnine.adapter.NoticeListAdapter$ViewHolder_ViewBinding.<init>(NoticeListAdapter$ViewHolder_ViewBinding.java:29)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance0(Native Method)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at butterknife.ButterKnife.createBinding(ButterKnife.java:199)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at butterknife.ButterKnife.bind(ButterKnife.java:172)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at club.ranleng.psnine.adapter.NoticeListAdapter$ViewHolder.<init>(NoticeListAdapter.java:76)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at club.ranleng.psnine.adapter.NoticeListAdapter.onCreateViewHolder(NoticeListAdapter.java:38)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at club.ranleng.psnine.adapter.NoticeListAdapter.onCreateViewHolder(NoticeListAdapter.java:23)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.View.layout(View.java:17641)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5575)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.View.layout(View.java:17641)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5575)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.View.layout(View.java:17641)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5575)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.View.layout(View.java:17641)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5575)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.View.layout(View.java:17641)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5575)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.View.layout(View.java:17641)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5575)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.View.layout(View.java:17641)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5575)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at com.android.internal.policy.DecorView.onLayout(DecorView.java:731)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.View.layout(View.java:17641)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.ViewGroup.layout(ViewGroup.java:5575)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
07-10 12:10:42.408 31295 31295 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
07-10 12:10:42.412  2166  3493 W ActivityManager:   Force finishing activity club.ranleng.psnine/.activity.Main.NoticeActivity
07-10 12:10:42.416  2166  3493 W ActivityManager:   Force finishing activity club.ranleng.psnine/.activity.Main.MainActivity
07-10 12:10:42.916  2166  2209 W ActivityManager: Activity pause timeout for ActivityRecord{c6e3cf5 u0 club.ranleng.psnine/.activity.Main.NoticeActivity t4281 f}
07-10 12:10:45.032  2166  3493 W ActivityManager:   Force finishing activity club.ranleng.psnine/.activity.Main.NoticeActivity
07-10 12:10:45.036  2166  3493 W ActivityManager:   Force finishing activity club.ranleng.psnine/.activity.Main.MainActivity
07-10 12:10:45.045  2166  3493 I ActivityManager: Killing 31295:club.ranleng.psnine/u0a250 (adj 900): crash
```

**Comment by RanKKI** [comment]
收到. 这个是我改布局之后忘记在代码里改类型了. 等下更新会修复这个问题.
